# Generated by Django 3.1.6 on 2021-03-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'verbose_name': 'Список заданий', 'verbose_name_plural': 'Списки заданий'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='ownerName',
        ),
        migrations.AddField(
            model_name='todolist',
            name='ownerName',
            field=models.CharField(blank='True', max_length=255, null=True, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='dateOfCreation',
            field=models.DateField(verbose_name='Дата cоздания'),
        ),
    ]
